DROP SCHEMA PU CASCADE; -- DROPT ook alle tables!

CREATE SCHEMA PU AUTHORIZATION DBA;

CREATE TABLE PU.BLOB(
	ID BIGINT NOT NULL,
	BLOB LONGVARBINARY,
	CLOB LONGVARCHAR,
	CONSTRAINT "PK-BLOB" PRIMARY KEY (ID)
);
	